#include <windows.h>
int WINAPI wWinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR pCmdLine, int nCmdShow) {
  HWND hide;
  MessageBox(NULL, L"Uamee - How to cook Pelmeshki", L"PELMESKI BLYAT", MK_OK | MB_ICONINFORMATION);
  while (true) {
    MessageBox(NULL, L"Food too cheap to meter", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"For the budget minded slavic eater", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Your wallet's walls are crumbling", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"How about this very tasty", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Russian dumplings", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Ha", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Bank account lower than", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Temperature Siberia", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Shto my blyat budyem yes't?", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Eto na mysteria", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"End of month condition has come", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Arrived to test me", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Thank God for slav food", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"By the name of pyelmyeshki", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"pyelmyeshki", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"pyelmyeshki", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"pyelmyeshki", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"pyelmyeshki", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Take a pot and put in water", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Somewhere over liter", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Toss bayleaf and pinch of salt", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Than place it onto heater", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Boullion cube is good addition", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"But some think it's overkill", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Even though it's end of month", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Why not try be gourmet still?", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"When water bubbles start to jump and", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Move to dance of pumping", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"It is time to dump in those", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Nice and frozen dumplings", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Take a spoon stir the pot", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Use it as a brushee", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Don't let dumplings stick to pot", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Unless you like them mushy", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Wait for boil", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Wait for boil", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Wait for boil", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Wait for boil", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"HaHaHa", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Bank account lower than", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Temperature Siberia", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Shto my blyat budyem yes't?", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Eto na mysteria", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"End of month condition has come", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Arrived to test me", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Thank God for slav food", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"By the name of pyelmyeshki", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"pyelmyeshki", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"pyelmyeshki", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"pyelmyeshki", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"pyelmyeshki", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Some minutes into boiling and", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"You see the dumplings floating", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Wait for like three minutes more", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"And then we start unloading", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Use whatever tool you have", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Perform the act of dishing", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"I like use the same spoon", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Because it feels like fishing", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Cut the onions", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Dice the dill", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Big spoon sourcream", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Seal the deal", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"All this food for just 1 Euro?", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Bank account lower than", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Temperature Siberia", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Shto my blyat budyem yes't?", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Eto na mysteria", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"End of month condition has come", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Arrived to test me", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Thank God for slav food", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"By the name of pyelmyeshki", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"I'm not a chef, dat boi just tourist", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"If you want to make yourself", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Go watch Life of Boris", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"HaHa", L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
    MessageBox(NULL, L"Uamee! Vaino Luke Čemeriov par mani :D #ŠņabisNoKrievijas", , L"PELMESHKI", MB_OK | MB_ICONINFORMATION);
}
}
